// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTinWRjJ3DmPL5c02TcKZ27H-L1_XcZRc',
    appId: '1:1092983347610:web:3f8edc8c037aa531ce4223',
    messagingSenderId: '1092983347610',
    projectId: 'socialmediapp-d07c4',
    authDomain: 'socialmediapp-d07c4.firebaseapp.com',
    storageBucket: 'socialmediapp-d07c4.appspot.com',
    measurementId: 'G-MYK4MPB7SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JR9cdD83ezAZQccVtnLiT3WL0nI1274',
    appId: '1:1092983347610:android:aa9c24525cd54084ce4223',
    messagingSenderId: '1092983347610',
    projectId: 'socialmediapp-d07c4',
    storageBucket: 'socialmediapp-d07c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAI5w5qifdLSxHh9d2jmWFJFMcJ1dTlA',
    appId: '1:1092983347610:ios:408888d67263dde7ce4223',
    messagingSenderId: '1092983347610',
    projectId: 'socialmediapp-d07c4',
    storageBucket: 'socialmediapp-d07c4.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAI5w5qifdLSxHh9d2jmWFJFMcJ1dTlA',
    appId: '1:1092983347610:ios:408888d67263dde7ce4223',
    messagingSenderId: '1092983347610',
    projectId: 'socialmediapp-d07c4',
    storageBucket: 'socialmediapp-d07c4.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTinWRjJ3DmPL5c02TcKZ27H-L1_XcZRc',
    appId: '1:1092983347610:web:a2c1b54ce6627ac6ce4223',
    messagingSenderId: '1092983347610',
    projectId: 'socialmediapp-d07c4',
    authDomain: 'socialmediapp-d07c4.firebaseapp.com',
    storageBucket: 'socialmediapp-d07c4.appspot.com',
    measurementId: 'G-R5YQ1HDBNG',
  );
}
